directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV2_AWS_8  #Ensure that RDS clusters has backup plan of AWS Backup
